[project]
name = "python-template"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
requires-python = ">=3.11"
dependencies = [
    "elevenlabs>=1.55.0",
    "flask>=3.1.0",
    "python-telegram-bot>=20.0,<21.0",
    "telegram>=0.0.1",
    "twilio>=9.5.1",
]
